languageCode = "en"
languageName = "English"
weight = 1
title = "Sandra Tang"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Sandra Tang"
  email = "st2232@cornell.edu"
  headline = "CS @ Cornell University"
 
  links = [
    { linkedin = "https://www.linkedin.com/in/sandra-tang-651ab1333/" },
    { github = "https://github.com/mcorgi" },
  ]